/*
 * Copyright (c) 2024 GLA Research and Development Directorate
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package org.grad.eNav.s100.utils;

import dk.dma.niord.s100.catalog._5_2.S100BoundingPolygonType;
import dk.dma.niord.s100.catalog._5_2.S100DataCoverage;
import dk.dma.niord.s100.catalog._5_2.S100DatasetDiscoveryMetadata;
import dk.dma.niord.s100.catalog._5_2.S100ExchangeCatalogue;
import dk.dma.niord.s100.catalog._5_2.S100GeographicBoundingBoxType;
import dk.dma.niord.s100.catalog._5_2.StandaloneDigitalSignature;
import jakarta.xml.bind.*;
import net.opengis.gml._3.*;
import org.iso.standards.iso._19115.__3.gco._1.CharacterStringPropertyType;
import org.iso.standards.iso._19115.__3.gco._1.CodeListValueType;
import org.iso.standards.iso._19115.__3.gco._1.DecimalPropertyType;
import org.iso.standards.iso._19115.__3.gco._1.ObjectFactory;
import org.iso.standards.iso._19115.__3.gmw._1.GMObjectPropertyType;
import org.iso.standards.iso._19115.__3.lan._1.CountryCodePropertyType;
import org.iso.standards.iso._19115.__3.lan._1.LanguageCodePropertyType;
import org.iso.standards.iso._19115.__3.lan._1.MDCharacterSetCodePropertyType;
import org.iso.standards.iso._19115.__3.lan._1.PTLocaleType;
import org.locationtech.jts.geom.*;

import java.io.ByteArrayInputStream;
import java.io.ByteArrayOutputStream;
import java.lang.Boolean;
import java.math.BigDecimal;
import java.math.BigInteger;
import java.nio.charset.StandardCharsets;
import java.security.cert.CertificateEncodingException;
import java.security.cert.CertificateException;
import java.security.cert.CertificateFactory;
import java.security.cert.X509Certificate;
import java.util.*;
import java.util.concurrent.atomic.AtomicLong;
import java.util.stream.Stream;

/**
 * The S-100 Exchange Set Utility Class.
 * <p/>
 * A static utility function class that allows easily manipulation of the S-100
 * Exchange Sets.
 *
 * @author Nikolaos Vastardis (email: Nikolaos.Vastardis@gla-rad.org)
 */
public class S100ExchangeSetUtils {

    /**
     * The Language Code namespace/list for use in the language codes. The
     * codeList attribute is required by the ISO 19115-3 CodeListValueType, so
     * it must not be null.
     */
    public static final String LANGUAGE_NAMESPACE = "ISO 639-2/T";
    public static final String LANGUAGE_LIST = "https://standards.iso.org/iso/19115/resources/Codelists/cat/codelists.xml";

    /**
     * The Country Code namespace/list for use in the country codes. The
     * codeList attribute is required by the ISO 19115-3 CodeListValueType, so
     * it must not be null.
     */
    public static final String COUNTRY_NAMESPACE = "ISO 3166-2";
    public static final String COUNTRY_LIST = "https://standards.iso.org/iso/19115/resources/Codelists/cat/codelists.xml";

    /**
     * The Character Set Encoding namespace/list for use in the character set encoding codes.
     */
    public static final String CHARACTER_ENCODING_NAMESPACE = null;
    public static final String CHARACTER_ENCODING_LIST = "http://www.iana.org/assignments/character-sets";

    /**
     * The prefix of the GML identifiers generated for the data coverage
     * bounding polygons. S-100 Part 17, S100_DataCoverage NOTE 1 requires that
     * "The GML polygon shall have a valid GML identifier", which - being a
     * gml:id - must also be unique inside the generated catalogue document.
     */
    public static final String BOUNDING_POLYGON_ID_PREFIX = "BP.";

    /**
     * The spatial reference system of the data coverage bounding polygons. S-100
     * Part 17, S100_DataCoverage NOTE 1 restricts them to Linear Rings "using SRS
     * EPSG:4326", so the CRS is named on the polygon itself; without srsName a
     * reader cannot tell which CRS - and therefore which axis order - the
     * positions are in.
     */
    public static final String BOUNDING_POLYGON_SRS_NAME = "EPSG:4326";

    /**
     * The counter providing the unique part of the bounding polygon GML
     * identifiers. All polygons of a catalogue are generated by the same JVM,
     * so a JVM-wide counter guarantees the required document uniqueness.
     */
    private static final AtomicLong BOUNDING_POLYGON_ID_COUNTER = new AtomicLong(1);

    /**
     * The JAXB context every catalogue read and write in this library goes through, created
     * once and reused.
     * <p/>
     * It is the package wide context rather than a class scoped one because that is what
     * resolves the S100_SE_DigitalSignature substitution group - a signature marshalled as
     * an S100_SE_SignatureOnData, the realization S-100 Part 15, clause 15-8.11.3, gives a
     * signature over a data resource, has to return as one. Every type this class marshals -
     * S100ExchangeCatalogue, S100DatasetDiscoveryMetadata and the Part 15
     * StandaloneDigitalSignature of CATALOG.SIGN - lives in that one package and is loaded by
     * the same class loader, so a single context serves them all.
     * <p/>
     * Building a context costs roughly 50ms, which dominates the cost of a marshal or an
     * unmarshal; a cancellation deep copies an entry through this class and an exchange set
     * marshals both a catalogue and its signature, so a producer withdrawing a batch of
     * warnings would otherwise pay that price tens of times per exchange set. JAXBContext is
     * documented thread safe and the package and class loader arguments are constant, so the
     * instance is safe to share; the Marshaller and Unmarshaller derived from it are not, and
     * are still created per call.
     */
    private static JAXBContext catalogueJaxbContext;

    /**
     * Returns the shared catalogue JAXB context, creating it on first use.
     * <p/>
     * The context is created lazily rather than in a static initialiser so that a JAXB
     * configuration failure surfaces as the declared JAXBException on the call that needs the
     * context, not as an ExceptionInInitializerError from an unrelated use of this class.
     * Synchronising the whole method costs an uncontended monitor acquire on a call that goes
     * on to marshal or parse a whole document, which is not a price worth a subtler idiom.
     *
     * @return the JAXB context covering the S-100 exchange catalogue package
     * @throws JAXBException for errors in creating the JAXB context
     */
    private static synchronized JAXBContext catalogueJaxbContext() throws JAXBException {
        if (catalogueJaxbContext == null) {
            catalogueJaxbContext = JAXBContext.newInstance(
                    S100ExchangeCatalogue.class.getPackageName(),
                    S100ExchangeCatalogue.class.getClassLoader());
        }
        return catalogueJaxbContext;
    }

    /**
     * Marshals an object of the S-100 exchange catalogue bindings through the shared context.
     * <p/>
     * The marshaller writes UTF-8 and declares it in the XML declaration, so the bytes are
     * decoded as UTF-8 and not with whatever the platform default charset happens to be: the
     * unmarshalling side re-encodes as UTF-8, and an exchange set writes these bytes into
     * CATALOG.XML as UTF-8, so decoding with anything else silently mangles every non-ASCII
     * character on the way out.
     *
     * @param object the object to marshal
     * @param format whether to format the XML string
     * @return the marshalled XML representation
     * @throws JAXBException for errors in the marshalling operation
     */
    private static String marshalCatalogueObject(Object object, Boolean format) throws JAXBException {
        Marshaller jaxbMarshaller = catalogueJaxbContext().createMarshaller();
        jaxbMarshaller.setProperty(Marshaller.JAXB_FORMATTED_OUTPUT, format);

        ByteArrayOutputStream xmlStream = new ByteArrayOutputStream();
        jaxbMarshaller.marshal(object, xmlStream);
        return xmlStream.toString(StandardCharsets.UTF_8);
    }

    /**
     * Unmarshals a document of the S-100 exchange catalogue bindings through the shared context.
     * <p/>
     * The document is parsed through {@link SecureXmlSource}, so a document type declaration is
     * refused rather than honoured; see there for what that closes and why no conformant
     * document of these bindings carries one.
     *
     * @param xml  the XML content
     * @param type the type the document is expected to unmarshal to
     * @return the unmarshalled object
     * @throws JAXBException for errors in the unmarshalling operation
     */
    private static <T> T unmarshalCatalogueObject(String xml, Class<T> type) throws JAXBException {
        Unmarshaller jaxbUnmarshaller = catalogueJaxbContext().createUnmarshaller();
        return type.cast(JAXBIntrospector.getValue(jaxbUnmarshaller.unmarshal(SecureXmlSource.of(xml))));
    }


    /**
     * A helper function to easily generate character string property types
     * that are used by the ISO standards.
     * <p/>
     * For null inputs this function returns null, so that optional elements
     * are omitted entirely; a JAXBElement wrapping a null value would be
     * marshalled as {@code xsi:nil="true"}, which the non-nillable
     * gco:CharacterString element does not allow.
     *
     * @param characterString The string to be transformed into a character string property type
     * @return The character string property type
     */
    public static CharacterStringPropertyType createCharacterStringPropertyType(String characterString) {
        if(Objects.isNull(characterString)) {
            return null;
        }
        final ObjectFactory objectFactory = new ObjectFactory();
        final CharacterStringPropertyType cspt = new CharacterStringPropertyType();
        cspt.setCharacterString(objectFactory.createCharacterString(characterString));
        return cspt;
    }

    /**
     * A helper function to easily generate a list of character string property
     * types that are used by the ISO standards. Null entries are skipped.
     *
     * @param characterStringList  The list of string to be transformed into a list of character string property type
     * @return The list of character string property type
     */
    public static List<CharacterStringPropertyType> createCharacterStringPropertyTypeList(List<String> characterStringList) {
        return Optional.ofNullable(characterStringList)
                .orElseGet(Collections::emptyList)
                .stream()
                .filter(Objects::nonNull)
                .map(S100ExchangeSetUtils::createCharacterStringPropertyType)
                .toList();
    }

    /**
     * A helper function to easily generate a decimal property type that is used
     * in the S-100.
     *
     * @param decimal the provided Java decimal object
     * @return the S-100 DecimalPropertyType object
     */
    public static DecimalPropertyType createDecimalPropertyType(BigDecimal decimal) {
        final DecimalPropertyType decimalPropertyType = new DecimalPropertyType();
        decimalPropertyType.setDecimal(decimal);
        return decimalPropertyType;
    }

    /**
     * For a given code list type class, a code list value and the actual input
     * this helper function will generate a code list value object.
     *
     * @param list the list location of the code list value type
     * @param space the space of the code list value type
     * @param code the code of the code list value type
     * @param input the actual value of the code list value type
     * @return the populated code list value type object
     */
    public static CodeListValueType createCodeListValueType(String list, String space, String code, String input) {
        final CodeListValueType codeListValueType = new CodeListValueType();
        codeListValueType.setCodeList(list);
        codeListValueType.setCodeSpace(space);
        codeListValueType.setCodeListValue(code);
        codeListValueType.setValue(input);
        return codeListValueType;
    }

    /**
     * Based on the provided Java Locale this function will generate the S-100
     * PTLocaleType object and return it.
     *
     * @param locale the Java locale object
     * @return the S-100 respective PTLocaleType object
     */
    public static PTLocaleType createPTLocaleType(Locale locale) {
        // Sanity check
        if(Objects.isNull(locale)) {
            return null;
        }

        // Otherwise continue
        final PTLocaleType ptLocaleValue = new PTLocaleType();
        LanguageCodePropertyType languageCodePropertyType = new LanguageCodePropertyType();
        languageCodePropertyType.setLanguageCode(S100ExchangeSetUtils.createCodeListValueType(
                LANGUAGE_LIST,
                LANGUAGE_NAMESPACE,
                locale.getISO3Language(),
                locale.getDisplayLanguage()));
        ptLocaleValue.setLanguage(languageCodePropertyType);
        // S-100 Part 17, PT_Locale: the country is an optional ISO 3166-1
        // 2-letter code, so locales without a country omit the element
        final String countryCode = locale.getCountry();
        if(!countryCode.isEmpty()) {
            CountryCodePropertyType countryCodePropertyType = new CountryCodePropertyType();
            countryCodePropertyType.setCountryCode(S100ExchangeSetUtils.createCodeListValueType(
                    COUNTRY_LIST,
                    COUNTRY_NAMESPACE,
                    countryCode,
                    locale.getDisplayCountry()));
            ptLocaleValue.setCountry(countryCodePropertyType);
        }
        MDCharacterSetCodePropertyType mdCharacterSetCodePropertyType = new MDCharacterSetCodePropertyType();
        mdCharacterSetCodePropertyType.setMDCharacterSetCode(S100ExchangeSetUtils.createCodeListValueType(
                CHARACTER_ENCODING_LIST,
                CHARACTER_ENCODING_NAMESPACE,
                StandardCharsets.UTF_8.name(),
                StandardCharsets.UTF_8.displayName()));
        ptLocaleValue.setCharacterEncoding(mdCharacterSetCodePropertyType);
        return ptLocaleValue;
    }

    /**
     * Based on the provided Java Geometry this function will generate the S-100
     * S100GeographicBoundingBoxType object and return it.
     *
     * @param geometry the Java geometry object
     * @return the S-100 respective S100GeographicBoundingBoxType object
     */
    public static S100GeographicBoundingBoxType createS100GeographicBoundingBoxType(Geometry geometry) {
        // Sanity Check
        if(Objects.isNull(geometry)) {
            return null;
        }

        // Create the geometry envelope
        final Envelope envelope = new Envelope();
        for(Coordinate coordinate : geometry.getCoordinates()) {
            envelope.expandToInclude(coordinate);
        }

        // Initialise a new bounding box type object
        S100GeographicBoundingBoxType boundingBoxType = new S100GeographicBoundingBoxType();

        // Populate the bounding box
        boundingBoxType.setWestBoundLongitude(createDecimalPropertyType(BigDecimal.valueOf(envelope.getMinX())));
        boundingBoxType.setEastBoundLongitude(createDecimalPropertyType(BigDecimal.valueOf(envelope.getMaxX())));
        boundingBoxType.setSouthBoundLatitude(createDecimalPropertyType(BigDecimal.valueOf(envelope.getMinY())));
        boundingBoxType.setNorthBoundLatitude(createDecimalPropertyType(BigDecimal.valueOf(envelope.getMaxY())));

        // And return the result
        return boundingBoxType;
    }

    /**
     * Based on the provided Java Geometry this function will generate the S-100
     * S100DataCoverage object and return it.
     * <p/>
     * Since S-100 Part 17 (S100_DataCoverage NOTE 1) restricts every bounding
     * polygon to a single GML polygon, geometry collections - including
     * multi-polygons - generate one data coverage entry per component geometry.
     *
     * @param geometry the Java geometry object
     * @return the S-100 respective S100DataCoverage object
     */
    public static List<S100DataCoverage> createS100DataCoverages(Geometry geometry) {
        // Sanity Check
        if(Objects.isNull(geometry)) {
            return null;
        }

        // Create the list of S-100 data coverage objects
        final List<S100DataCoverage> dataCoverages = new ArrayList<>();

        // Build the list of data coverage objects checking for collections
        if(geometry instanceof GeometryCollection geometryCollection) {
            for(int i=0; i<geometryCollection.getNumGeometries(); i++) {
                dataCoverages.addAll(createS100DataCoverages(geometryCollection.getGeometryN(i)));
            }
        } else {
            // Initialise a new data coverage object
            final S100DataCoverage dataCoverage = new S100DataCoverage();

            // Populate the data coverage
            final S100BoundingPolygonType boundingPolygonType = new S100BoundingPolygonType();
            final GMObjectPropertyType gmObjectPropertyType = new GMObjectPropertyType();
            gmObjectPropertyType.setAbstractGeometry(new net.opengis.gml._3.ObjectFactory()
                    .createPolygon(generateBoundingPolygon(geometry)));
            boundingPolygonType.setPolygons(Collections.singletonList(gmObjectPropertyType));
            dataCoverage.setBoundingPolygon(boundingPolygonType);

            // And add it to the list
            dataCoverages.add(dataCoverage);
        }

        // Finally return the populated list
        return dataCoverages;
    }

    /**
     * Overloading the S100ExchangeSet marshalling operation to easily perform
     * the task with the formatting turned on by default.
     *
     * @param s100ExchangeCatalogue the S100 Exchange Set Catalogue object
     * @return the marshalled S100 Exchange Set Catalogue XML representation
     * @throws JAXBException for errors in the marshalling operation
     */
    public static String marshalS100ExchangeSetCatalogue(S100ExchangeCatalogue s100ExchangeCatalogue) throws JAXBException {
        return marshalS100ExchangeSetCatalogue(s100ExchangeCatalogue, Boolean.TRUE);
    }

    /**
     * Using the S100ExchangeSet utilities we can marshall S100ExchangeCatalogue
     * objects to the XML representation.
     *
     * @param s100ExchangeCatalogue the S100 Exchange Set Catalogue object
     * @param format whether to format the XML string
     * @return the marshalled S100 Exchange Set Catalogue XML representation
     * @throws JAXBException for errors in the marshalling operation
     */
    public static String marshalS100ExchangeSetCatalogue(S100ExchangeCatalogue s100ExchangeCatalogue, Boolean format) throws JAXBException {
        return marshalCatalogueObject(s100ExchangeCatalogue, format);
    }

    /**
     * Marshals the Part 15 StandaloneDigitalSignature document an exchange set carries as
     * CATALOG.SIGN, which signs the catalogue bytes themselves.
     * <p/>
     * S-100 Part 15, clauses 15-8.7 and 15-8.11.2, require an auxiliary file the catalogue
     * metadata does not cover - the catalogue above all - to be signed with a self-contained
     * document carrying the signed file name, every certificate needed to authenticate the
     * signature and the signature itself, rather than with a bare signature value.
     *
     * @param signature the standalone digital signature document
     * @param format whether to format the XML string
     * @return the marshalled StandaloneDigitalSignature XML representation
     * @throws JAXBException for errors in the marshalling operation
     */
    public static String marshalStandaloneDigitalSignature(StandaloneDigitalSignature signature, Boolean format) throws JAXBException {
        return marshalCatalogueObject(signature, format);
    }

    /**
     * Wraps a signature in the element S-100 Part 15 declares for its concrete type, for a
     * {@code digitalSignatureValue} of the exchange catalogue.
     * <p/>
     * Part 15 declares {@code S100_SE_SignatureOnData} and {@code S100_SE_SignatureOnSignature} as
     * substitution-group members of {@code S100_SE_DigitalSignature}, so the same signature can be
     * written either as its own element or as the head element with an {@code xsi:type}. Both are
     * schema-valid and the same to a schema-aware reader, but a catalogue that spells the two forms
     * side by side - which happens as soon as an entry built here is reproduced by a fileless
     * cancellation (S-100 Part 17, clause 17-4.4.1) - is needlessly two things to a reader that
     * matches on element names. Every builder in this package therefore writes the member element
     * whenever the signature has a concrete type, and the head element only for the base type.
     *
     * @param signature the signature to wrap
     * @return the JAXB element for the signature's concrete type
     */
    public static JAXBElement<? extends dk.dma.niord.s100.catalog._5_2.S100SEDigitalSignature> digitalSignatureElement(
            dk.dma.niord.s100.catalog._5_2.S100SEDigitalSignature signature) {
        final dk.dma.niord.s100.catalog._5_2.ObjectFactory objectFactory = new dk.dma.niord.s100.catalog._5_2.ObjectFactory();
        if (signature instanceof dk.dma.niord.s100.catalog._5_2.S100SESignatureOnData onData) {
            return objectFactory.createS100SESignatureOnData(onData);
        }
        if (signature instanceof dk.dma.niord.s100.catalog._5_2.S100SESignatureOnSignature onSignature) {
            return objectFactory.createS100SESignatureOnSignature(onSignature);
        }
        return objectFactory.createS100SEDigitalSignature(signature);
    }

    /**
     * The character string input object contains the XML content of the S100
     * Exchange Set Catalogue. We can easily translate that into an
     * S100ExchangeCatalogue object so that it can be accessed more efficiently.
     * <p/>
     * A catalogue reaches this method from an archive, which the reader may not
     * have produced - a SECOM peer's exchange set is a realistic input - so it is
     * parsed through {@link SecureXmlSource}, which refuses a document type
     * declaration. A schema-valid catalogue never carries one (S-100 Part 17,
     * clause 17-4.2), and one that does fails as a JAXBException, the same way
     * malformed XML already does.
     *
     * @param s100ExchangeCatalogue the S100 Exchange Set Catalogue XML content
     * @return The unmarshalled 100 Exchange Set Catalogue object
     * @throws JAXBException for errors in the unmarshalling operation, including a
     *                       document that declares a DOCTYPE or an external entity
     */
    public static S100ExchangeCatalogue unmarshallS100ExchangeSetCatalogue(String s100ExchangeCatalogue) throws JAXBException {
        return unmarshalCatalogueObject(s100ExchangeCatalogue, S100ExchangeCatalogue.class);
    }

    /**
     * Overloading the S100 dataset discovery metadata marshalling operation to
     * easily perform the task with the formatting turned on by default.
     * <p/>
     * The unformatted output of the two argument overload is the one to store,
     * being appreciably smaller; both forms parse into equivalent entries, so
     * comparing the output of the two as strings is meaningless.
     *
     * @param metadata the S100 dataset discovery metadata object
     * @return the marshalled S100 dataset discovery metadata XML representation
     * @throws JAXBException for errors in the marshalling operation
     */
    public static String marshalS100DatasetDiscoveryMetadata(S100DatasetDiscoveryMetadata metadata) throws JAXBException {
        return marshalS100DatasetDiscoveryMetadata(metadata, Boolean.TRUE);
    }

    /**
     * Using the S100ExchangeSet utilities we can marshall a single
     * S100DatasetDiscoveryMetadata entry to its XML representation, separately
     * from the exchange catalogue that carries it. The type is an XML root
     * element in its own right, so a single entry round-trips on its own.
     * <p/>
     * A producer stores an entry in this form between publishing a dataset and
     * cancelling it: S-100 Part 17, clause 17-4.4.1, cancels a dataset with an
     * entry that reproduces the published one, so the published entry has to
     * outlive the exchange catalogue it was delivered in.
     *
     * @param metadata the S100 dataset discovery metadata object
     * @param format whether to format the XML string
     * @return the marshalled S100 dataset discovery metadata XML representation
     * @throws JAXBException for errors in the marshalling operation
     */
    public static String marshalS100DatasetDiscoveryMetadata(S100DatasetDiscoveryMetadata metadata, Boolean format) throws JAXBException {
        return marshalCatalogueObject(metadata, format);
    }

    /**
     * The character string input object contains the XML content of a single
     * S100 dataset discovery metadata entry, as written by
     * {@link #marshalS100DatasetDiscoveryMetadata(S100DatasetDiscoveryMetadata)}.
     * We can easily translate that back into an S100DatasetDiscoveryMetadata
     * object, ready to be reproduced in a cancellation entry.
     * <p/>
     * The shared package wide context is what resolves the S100_SE_DigitalSignature
     * substitution group, so a stored signature returns as the S100_SE_SignatureOnData
     * it was marshalled as.
     * <p/>
     * The entry is parsed through {@link SecureXmlSource}, which refuses a document
     * type declaration. The stored string is usually the producer's own column, but it
     * is the {@code original} of a cancellation and can equally have been recovered
     * from a foreign archive - and an entry that has sat in a database since it was
     * published is exactly the kind of value whose provenance nobody re-checks at read
     * time.
     *
     * @param metadataXml the S100 dataset discovery metadata XML content
     * @return The unmarshalled S100 dataset discovery metadata object
     * @throws JAXBException for errors in the unmarshalling operation, including a
     *                       document that declares a DOCTYPE or an external entity
     */
    public static S100DatasetDiscoveryMetadata unmarshallS100DatasetDiscoveryMetadata(String metadataXml) throws JAXBException {
        return unmarshalCatalogueObject(metadataXml, S100DatasetDiscoveryMetadata.class);
    }

    /**
     * This helper function will read the provided certificate and will generate
     * a minified version of its PEM representation, i.e. the ASCII characters of
     * the Base64 encoded certificate DER content, without the PEM header and
     * footer lines. Turned into a string it is the exact inverse of
     * {@link #getCertFromPem(String)}.
     * <p/>
     * Note that this is the <b>textual</b> PEM representation. The certificate
     * and signature elements of the S-100 protection scheme are typed
     * xs:base64Binary, which JAXB Base64-encodes on its own, so those elements
     * must be handed the DER content of {@link #getDerFromCert(X509Certificate)}
     * instead - passing them the PEM text would encode the certificate twice.
     *
     * @param cert the X.509 certificate to be read
     * @return the minified PEM representation of the certificate
     * @throws CertificateEncodingException if the provided certificate is invalid
     */
    public static byte[] getPemFromCert(X509Certificate cert) throws CertificateEncodingException {
        return Base64.getEncoder().encode(cert.getEncoded());
    }

    /**
     * This helper function will read the provided certificate and will return
     * its DER content, for embedding into the xs:base64Binary-typed certificate
     * elements of the S-100 protection scheme.
     * <p/>
     * S-100 Part 15, clauses 15-8.6 and 15-8.11.1, require such an element to
     * carry the Base64 encoded X.509 certificate - "When embedding the digital
     * certificates in XML elements, the header and footer lines are omitted" -
     * so a single Base64 decode of the element content has to yield the
     * certificate itself. Since JAXB performs that Base64 encoding for the
     * xs:base64Binary value, the value it is given must be the raw DER content.
     *
     * @param cert the X.509 certificate to be read
     * @return the DER content of the certificate
     * @throws CertificateEncodingException if the provided certificate is invalid
     */
    public static byte[] getDerFromCert(X509Certificate cert) throws CertificateEncodingException {
        return cert.getEncoded();
    }

    /**
     * This helper function will read the provided PEM input and reconstruct the
     * valid X509 certificate.
     *
     * @param certificatePem the certificate PEM input, i.e. the Base64 encoded
     *                       certificate without the PEM header and footer lines
     * @return the valid X509 certificate
     * @throws CertificateException if the provided PEM file is invalid
     */
    public static X509Certificate getCertFromPem(String certificatePem) throws CertificateException {
        // First decode the Base64 encoded PEM format
        final byte[] decodedPem = Base64.getDecoder().decode(certificatePem);

        // Then reconstruct the X509Certificate object
        return (X509Certificate) CertificateFactory.getInstance("X.509")
                .generateCertificate(new ByteArrayInputStream(decodedPem));
    }

    /**
     * Populates and return an S-100 surface property based on the provided
     * surface geometry coordinates.
     *
     * @param coords    The coordinates of the element to be generated
     * @return The populated point property
     */
    protected static PolygonPatchType generateSurfacePropertyPatch(Double[] coords) {
        // Create an OpenGIS GML factory
        net.opengis.gml._3.ObjectFactory opengisGMLFactory = new net.opengis.gml._3.ObjectFactory();

        // Generate the elements
        PolygonPatchType polygonPatchType = new PolygonPatchType();
        AbstractRingPropertyType abstractRingPropertyType = new AbstractRingPropertyType();
        LinearRingType linearRingType = new LinearRingType();
        PosList posList = new PosList();

        // Populate with the geometry data
        posList.setValue(coords);

        // Populate the elements
        linearRingType.setPosList(posList);
        abstractRingPropertyType.setAbstractRing(opengisGMLFactory.createLinearRing(linearRingType));
        polygonPatchType.setExterior(abstractRingPropertyType);

        // And return the output
        return polygonPatchType;
    }

    /**
     * Populates and returns the GML polygon used as the bounding polygon of a
     * single S-100 data coverage entry.
     * <p/>
     * S-100 Part 17, S100_DataCoverage NOTE 1 restricts the bounding polygon to
     * "a single GML Polygon with one exterior and 0 or more interiors expressed
     * as Linear Rings using SRS EPSG:4326", so the shell and the holes of a
     * polygon are encoded as separate linear rings and never merged. Any other
     * (non-polygonal) geometry is described by its envelope, which is the
     * smallest rectangle satisfying the closed, at least 4 positions rule.
     *
     * @param geometry the Java geometry object, not a geometry collection
     * @return The populated bounding polygon
     */
    protected static PolygonType generateBoundingPolygon(Geometry geometry) {
        // Generate the elements
        final PolygonType polygonType = new PolygonType();

        // NOTE 1 also requires a valid GML identifier for the polygon
        polygonType.setId(BOUNDING_POLYGON_ID_PREFIX + BOUNDING_POLYGON_ID_COUNTER.getAndIncrement());
        // NOTE 1 fixes the SRS of the bounding polygon to EPSG:4326, whose axis order is
        // the latitude/longitude order the ring coordinates are written in below
        polygonType.setSrsName(BOUNDING_POLYGON_SRS_NAME);
        // srsDimension is the coordinate dimension (lat/lon), not the SRID
        polygonType.setSrsDimension(BigInteger.TWO);

        // Populate the exterior and the optional interiors
        if(geometry instanceof Polygon polygon) {
            polygonType.setExterior(generateLinearRingProperty(polygon.getExteriorRing().getCoordinates()));
            final List<AbstractRingPropertyType> interiors = new ArrayList<>();
            for(int i=0; i<polygon.getNumInteriorRing(); i++) {
                interiors.add(generateLinearRingProperty(polygon.getInteriorRingN(i).getCoordinates()));
            }
            if(!interiors.isEmpty()) {
                polygonType.setInteriors(interiors);
            }
        } else {
            polygonType.setExterior(generateLinearRingProperty(envelopeToRingCoordinates(geometry)));
        }

        // And return the output
        return polygonType;
    }

    /**
     * Populates and returns an S-100 linear ring property based on the provided
     * ring geometry coordinates.
     * <p/>
     * Per S-100 Part 17, S100_DataCoverage NOTE 1 the exterior and the optional
     * interiors "shall be composed of a closed sequence of >=4 coordinate
     * positions", which is validated here so that non-conformant rings are
     * rejected instead of being marshalled.
     *
     * @param coordinates The ring coordinates of the element to be generated
     * @return The populated ring property
     */
    protected static AbstractRingPropertyType generateLinearRingProperty(Coordinate[] coordinates) {
        // Sanity check
        if(coordinates.length < 4 || !coordinates[0].equals2D(coordinates[coordinates.length-1])) {
            throw new IllegalArgumentException("The S-100 data coverage bounding polygon rings must be closed "
                    + "sequences of at least 4 coordinate positions (S-100 Part 17, S100_DataCoverage NOTE 1)");
        }

        // Create an OpenGIS GML factory
        net.opengis.gml._3.ObjectFactory opengisGMLFactory = new net.opengis.gml._3.ObjectFactory();

        // Generate the elements
        AbstractRingPropertyType abstractRingPropertyType = new AbstractRingPropertyType();
        LinearRingType linearRingType = new LinearRingType();
        PosList posList = new PosList();

        // Populate with the geometry data
        posList.setValue(coordinatesToArray(coordinates)
                .stream()
                .flatMap(Stream::of)
                .toArray(Double[]::new));

        // Populate the elements
        linearRingType.setPosList(posList);
        abstractRingPropertyType.setAbstractRing(opengisGMLFactory.createLinearRing(linearRingType));

        // And return the output
        return abstractRingPropertyType;
    }

    /**
     * A simple utility function that returns the closed ring of coordinates
     * describing the envelope of the provided geometry.
     *
     * @param geometry the provided geometry
     * @return the closed ring of coordinates of the geometry envelope
     */
    protected static Coordinate[] envelopeToRingCoordinates(Geometry geometry) {
        final Envelope envelope = geometry.getEnvelopeInternal();

        // Sanity check
        if(envelope.isNull()) {
            throw new IllegalArgumentException("The S-100 data coverage bounding polygon cannot be generated for "
                    + "an empty geometry (S-100 Part 17, S100_DataCoverage NOTE 1)");
        }

        // And return the envelope rectangle, closed as required
        return new Coordinate[] {
                new Coordinate(envelope.getMinX(), envelope.getMinY()),
                new Coordinate(envelope.getMaxX(), envelope.getMinY()),
                new Coordinate(envelope.getMaxX(), envelope.getMaxY()),
                new Coordinate(envelope.getMinX(), envelope.getMaxY()),
                new Coordinate(envelope.getMinX(), envelope.getMinY())
        };
    }

    /**
     * A simple utility function that receives JTS geometry coordinates and
     * constructs a list of the coordinate values arrays.
     *
     * @param coordinates the provided coordinates
     * @return the respective list of coordinate values arrays
     */
    protected static List<Double[]> coordinatesToArray(Coordinate[] coordinates) {
        // Translate the coordinates to a simple list of doubles (Y, X), i.e.
        // latitude followed by longitude, which is the EPSG:4326 axis order
        // mandated for the bounding polygons by S-100 Part 17
        return Optional.ofNullable(coordinates)
                .map(Arrays::asList)
                .orElse(Collections.emptyList())
                .stream()
                .map(c -> new Double[]{c.getY(), c.getX()})
                .toList();
    }

}
